/**
 * tabloKayitlari.js — hangi sayfada hangi sutunlar var?
 *
 * "Gorunumu Ozellestir" sayfasi, tablolari tek tek gezmeden sutunlari
 * duzenleyebilmek icin bu listeyi kullanir. Tablolarin KENDISI bu dosyaya
 * bakmaz; onlar kendi kolon tanimlariyla calisir ve tercihleri id uzerinden
 * okur. Yani buradaki bir eksiklik tabloyu bozmaz, yalnizca merkezi
 * panelde o sutun listelenmez.
 *
 * ⚠️ Bir sayfaya yeni sutun eklerken buraya da eklemeyi unutma.
 *
 * optional: true  -> varsayilanda gizli, "Baglanabilir veri sutunlari"
 *                    bolumunde cikar.
 */
export const TABLO_KAYITLARI = [
  {
    anahtar: 'urunler',
    ad: "Ürünler",
    sayfa: 'Products',
    sutunlar: [
      { id: 'sku', etiket: "SKU" },
      { id: 'name', etiket: "Ürün Adı" },
      { id: 'cost', etiket: "Maliyet" },
      { id: 'printing_cost', etiket: "Baskı Maliyeti" },
      { id: 'extra_cost', etiket: "Ek Maliyet" },
      { id: 'desi', etiket: "Desi" },
      { id: 'vat_rate', etiket: "KDV" },
      { id: 'same_day_delivery', etiket: "Bugün Kargoda" },
      { id: 'double_shipping', etiket: "Çift Kargo" },
      { id: 'paket', etiket: "Paket" },
      { id: 'is_active', etiket: "Durum" },
      { id: 'islemler', etiket: "İşlemler" },
      { id: 'barcode', etiket: "Barkod", optional: true },
      { id: 'unit_quantity', etiket: "Birim Adet", optional: true },
      { id: 'base_cost', etiket: "Baz Maliyet", optional: true },
      { id: 'notes', etiket: "Notlar", optional: true },
      { id: 'created_at', etiket: "Eklenme Tarihi", optional: true },
    ],
  },
  {
    anahtar: 'fiyatlar-platform',
    ad: "Fiyatlar — Platform sütunlu",
    sayfa: 'Prices',
    sutunlar: [
      { id: 'sku', etiket: "SKU" },
      { id: 'name', etiket: "Ürün Adı" },
      { id: 'cost', etiket: "Maliyet" },
      { id: 'printing_cost', etiket: "Baskı" },
      { id: 'extra_cost', etiket: "Ek Maliyet" },
      { id: 'barcode', etiket: "Barkod", optional: true },
      { id: 'vat_rate', etiket: "KDV Oranı", optional: true },
      { id: 'same_day_delivery', etiket: "Bugün Kargoda", optional: true },
      { id: 'notes', etiket: "Notlar", optional: true },
    ],
  },
  {
    anahtar: 'fiyatlar-satir',
    ad: "Fiyatlar — Satır bazlı",
    sayfa: 'Prices',
    sutunlar: [
      { id: 'sku', etiket: "SKU" },
      { id: 'name', etiket: "Ürün Adı" },
      { id: 'platform', etiket: "Platform" },
      { id: 'cost', etiket: "Maliyet" },
      { id: 'sale_price', etiket: "Satış Fiyatı" },
      { id: 'profit', etiket: "Kâr" },
      { id: 'profit_rate', etiket: "Kâr Oranı" },
      { id: 'barem', etiket: "Barem" },
      { id: 'detay', etiket: "Detay" },
    ],
  },
  {
    anahtar: 'komisyonlar',
    ad: "Komisyon & Hedef Kâr",
    sayfa: 'Commissions',
    sutunlar: [
      { id: 'platform_name', etiket: "Platform" },
      { id: 'category_name', etiket: "Kategori" },
      { id: 'commission_rate', etiket: "commission_rate" },
      { id: 'commission_vat_rate', etiket: "Komisyon KDV" },
      { id: 'target_profit_amount_sort', etiket: "Kâr Hedefleri" },
      { id: 'discounted_target_profit_amount_sort', etiket: "İndirimli Kâr Hedefleri" },
      { id: 'durum', etiket: "Durum" },
      { id: 'islemler', etiket: "İşlemler" },
      { id: 'minimum_profit_amount', etiket: "Minimum Kâr", optional: true },
      { id: 'target_profit_amount', etiket: "Hedef Kâr Tutarı", optional: true },
      { id: 'discounted_target_profit_rate', etiket: "İndirimli Hedef Kâr %", optional: true },
      { id: 'transaction_fee', etiket: "İşlem Ücreti", optional: true },
    ],
  },
  {
    anahtar: 'kargo-tarifeleri',
    ad: "Kargo Tarifeleri",
    sayfa: 'ShippingRates',
    sutunlar: [
      { id: 'platform_name', etiket: "Platform" },
      { id: 'shipping_company', etiket: "Kargo Firması" },
      { id: 'rate_type', etiket: "Tarife Tipi" },
      { id: 'fiyat_araligi', etiket: "Fiyat Aralığı" },
      { id: 'desi', etiket: "Desi" },
      { id: 'price', etiket: "Ücret" },
      { id: 'vat_rate', etiket: "KDV" },
      { id: 'durum', etiket: "Durum" },
      { id: 'islemler', etiket: "İşlemler" },
      { id: 'same_day_delivery', etiket: "Bugün Kargoda", optional: true },
      { id: 'is_manual', etiket: "Kaynak", optional: true },
      { id: 'updated_date', etiket: "Güncellenme Tarihi", optional: true },
    ],
  },
  {
    anahtar: 'kategoriler',
    ad: "Kategoriler",
    sayfa: 'Categories',
    sutunlar: [
      { id: 'name', etiket: "Kategori Adı" },
      { id: 'default_vat_rate', etiket: "Varsayılan KDV" },
      { id: '__pcount', etiket: "Ürün Sayısı" },
      { id: 'is_active', etiket: "Durum" },
      { id: 'islemler', etiket: "İşlemler" },
      { id: 'description', etiket: "Açıklama", optional: true },
      { id: 'created_at', etiket: "Eklenme Tarihi", optional: true },
    ],
  },
  {
    anahtar: 'paketleme',
    ad: "Paketleme",
    sayfa: 'PackageManagement',
    sutunlar: [
      { id: 'name', etiket: "Paket Adı" },
      { id: 'group', etiket: "Grup" },
      { id: 'desi_araligi', etiket: "Desi Aralığı" },
      { id: 'toplam_maliyet', etiket: "Toplam Maliyet" },
      { id: 'aktif', etiket: "Aktif" },
      { id: 'islemler', etiket: "İşlemler" },
      { id: 'description', etiket: "Açıklama", optional: true },
      { id: 'created_at', etiket: "Eklenme Tarihi", optional: true },
    ],
  },
  {
    anahtar: 'guncelleme-raporlari',
    ad: "Güncelleme Raporları",
    sayfa: 'UpdateReports',
    sutunlar: [
      { id: 'created_date', etiket: "Tarih" },
      { id: 'urun', etiket: "Ürün" },
      { id: 'platform_name', etiket: "Platform" },
      { id: 'old_sale_price', etiket: "Eski Fiyat" },
      { id: 'new_sale_price', etiket: "Yeni Fiyat" },
      { id: 'degisim', etiket: "Değişim" },
      { id: 'old_profit_rate', etiket: "Eski Kâr" },
      { id: 'new_profit_rate', etiket: "Yeni Kâr" },
      { id: 'change_type', etiket: "Neden" },
      { id: 'product_sku', etiket: "SKU", optional: true },
      { id: 'update_type', etiket: "Güncelleme Tipi", optional: true },
      { id: 'change_reason', etiket: "Değişim Sebebi", optional: true },
      { id: 'notes', etiket: "Notlar", optional: true },
    ],
  },
  {
    anahtar: 'pazaryeri-urunleri',
    ad: "Pazaryeri Ürünleri",
    sayfa: 'MarketplaceProducts',
    sutunlar: [
      { id: 'platform_account', etiket: "Platform" },
      { id: 'barkod', etiket: "Barkod" },
      { id: 'model_code', etiket: "Model Kodu" },
      { id: 'platform_product_name', etiket: "Ürün Adı" },
      { id: 'matched_product', etiket: "Bağlı Ürün" },
      { id: 'status', etiket: "Durum" },
      { id: 'brand', etiket: "Marka", optional: true },
      { id: 'category', etiket: "Kategori", optional: true },
      { id: 'marketplace_sale_price', etiket: "Pazaryeri Fiyatı", optional: true },
      { id: 'stock_quantity', etiket: "Stok", optional: true },
      { id: 'variant_sku', etiket: "Varyant SKU", optional: true },
    ],
  },
  {
    anahtar: 'duzenlenen-fiyatlar',
    ad: "Düzenlenen Fiyatlar",
    sayfa: 'UpdatedPrices',
    sutunlar: [
      { id: 'platform_product_name', etiket: "Platform Ürün Adı" },
      { id: 'product_name', etiket: "Sistem Ürünü" },
      { id: 'hb_sku', etiket: "SKU" },
      { id: 'platform_product_name', etiket: "Ürün Adı" },
      { id: 'stock_quantity', etiket: "Stok" },
      { id: 'barkod', etiket: "Barkod" },
      { id: 'platform_product_name', etiket: "Ürün Adı" },
      { id: 'stock_quantity', etiket: "Stok" },
      { id: 'product_sku', etiket: "Sistem Ürünü SKU", optional: true },
      { id: 'barkod_ek', etiket: "Barkod", optional: true },
    ],
  },
  {
    anahtar: 'duzenlenen-maliyetler',
    ad: "Düzenlenen Maliyetler",
    sayfa: 'UpdatedCosts',
    sutunlar: [
      { id: 'hb_sku', etiket: "HB Sku" },
      { id: 'barkod', etiket: "Barkod" },
      { id: 'merchant_sku', etiket: "Merchant Sku" },
      { id: 'barkod', etiket: "Barkod" },
      { id: 'model_code', etiket: "Model Kodu" },
      { id: 'merchant_sku', etiket: "Stok Kodu" },
      { id: 'category', etiket: "Kategori" },
      { id: 'product_name', etiket: "Ürün Adı" },
      { id: 'sale_price', etiket: "sale_price" },
      { id: 'stock', etiket: "Stok" },
      { id: 'cost', etiket: "Maliyet (KDV Dahil)" },
      { id: 'vat_rate', etiket: "KDV Oranı" },
      { id: 'currency', etiket: "Para Birimi" },
      { id: 'desi', etiket: "Desi" },
      { id: 'extra_cost_pct', etiket: "Ekstra Maliyet (%)" },
      { id: 'extra_cost', etiket: "Ekstra Maliyet (TL)" },
      { id: 'brand', etiket: "Marka", optional: true },
      { id: 'printing_cost', etiket: "Baskı Maliyeti", optional: true },
    ],
  }
];

export const kayitBul = (anahtar) =>
  TABLO_KAYITLARI.find(t => t.anahtar === anahtar) || null;
